/**
 * Histórico de exemplo da sincronização Sistema → CRM (RD Station), coerente
 * com os estados de SYNC_MOCK em mockLeads.ts: envios com sucesso (criação e
 * atualizações do Closer) e as duas falhas pendentes (lead-1 na criação,
 * lead-7 na atualização — esta com uma tentativa anterior também falha).
 */
import type { LogSincronizacaoCRM } from './crmSync'

export const MOCK_SYNC_LOGS: LogSincronizacaoCRM[] = [
  {
    id: 'sync-mock-08',
    leadId: 'lead-1',
    leadNome: 'Dra. Helena Marques',
    tipo: 'criacao',
    status: 'erro',
    provider: 'rd_station',
    payloadEnviado: {
      name: 'Dra. Helena Marques',
      company: 'Clínica Bem Viver',
      personal_phone: '(11) 98888-1010',
      source: 'Instagram',
      origem_sistema: 'Social Selling · domus',
    },
    respostaErro: 'Token de acesso expirado (401). Reautentique a integração no CRM.',
    timestamp: '2026-09-24T17:48:00',
  },
  {
    id: 'sync-mock-07',
    leadId: 'lead-7',
    leadNome: 'Dr. Otávio Prado',
    tipo: 'atualizacao',
    status: 'erro',
    provider: 'rd_station',
    payloadEnviado: { id: 'rd_46851', deal_stage: 'Perdido', deal_lost_reason: 'Preço', annotation: 'Não fechou — motivo: Preço' },
    respostaErro: 'CRM indisponível no momento (503). Tente novamente em instantes.',
    timestamp: '2026-09-24T11:31:00',
  },
  {
    id: 'sync-mock-06',
    leadId: 'lead-7',
    leadNome: 'Dr. Otávio Prado',
    tipo: 'atualizacao',
    status: 'erro',
    provider: 'rd_station',
    payloadEnviado: { id: 'rd_46851', deal_stage: 'Perdido', deal_lost_reason: 'Preço', annotation: 'Não fechou — motivo: Preço' },
    respostaErro: 'Limite de requisições da API atingido (429). Aguarde e tente de novo.',
    timestamp: '2026-09-24T11:02:00',
  },
  {
    id: 'sync-mock-05',
    leadId: 'lead-5',
    leadNome: 'Dra. Lívia Nunes',
    tipo: 'atualizacao',
    status: 'sucesso',
    provider: 'rd_station',
    payloadEnviado: {
      id: 'rd_47120',
      deal_stage: 'Em negociação',
      annotation: 'Follow-up: próximo contato em 18/09/2026 — Proposta enviada. Cliente pediu pra alinhar com o sócio.',
    },
    timestamp: '2026-09-23T12:10:00',
  },
  {
    id: 'sync-mock-04',
    leadId: 'lead-12',
    leadNome: 'Dr. Gustavo Pinto',
    tipo: 'atualizacao',
    status: 'sucesso',
    provider: 'rd_station',
    payloadEnviado: { id: 'rd_47655', deal_stage: 'Reunião não realizada', annotation: 'No-show na reunião. Reagendada para 23/09/2026 11:00' },
    timestamp: '2026-09-22T16:40:00',
  },
  {
    id: 'sync-mock-03',
    leadId: 'lead-11',
    leadNome: 'Dra. Beatriz Lopes',
    tipo: 'criacao',
    status: 'sucesso',
    provider: 'rd_station',
    payloadEnviado: {
      name: 'Dra. Beatriz Lopes',
      company: 'Clínica Sorriso Real',
      personal_phone: '(85) 90000-3344',
      source: 'Prospecção Instagram',
      origem_sistema: 'Social Selling · domus',
    },
    timestamp: '2026-09-21T15:30:00',
  },
  {
    id: 'sync-mock-02',
    leadId: 'lead-13',
    leadNome: 'Dra. Tânia Moreira',
    tipo: 'atualizacao',
    status: 'sucesso',
    provider: 'rd_station',
    payloadEnviado: { id: 'rd_47402', deal_stage: 'Ganho', amount_total: 36000, annotation: 'Negócio fechado · MRR 3000 · caixa recolhido 3200' },
    timestamp: '2026-09-18T11:05:00',
  },
  {
    id: 'sync-mock-01',
    leadId: 'lead-6',
    leadNome: 'Dr. Marcelo Vidal',
    tipo: 'atualizacao',
    status: 'sucesso',
    provider: 'rd_station',
    payloadEnviado: { id: 'rd_46988', deal_stage: 'Ganho', amount_total: 48000, annotation: 'Negócio fechado · MRR 4000 · caixa recolhido 4200' },
    timestamp: '2026-09-17T17:55:00',
  },
]
